/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSolarRouteImport } from './routes/services/solar'
import { Route as ServicesPrefabRouteImport } from './routes/services/prefab'
import { Route as ServicesEdiblePrintingRouteImport } from './routes/services/edible-printing'
import { Route as ServicesAdvertisingRouteImport } from './routes/services/advertising'
import { Route as Services3dPrintingRouteImport } from './routes/services/3d-printing'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSolarRoute = ServicesSolarRouteImport.update({
  id: '/services/solar',
  path: '/services/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrefabRoute = ServicesPrefabRouteImport.update({
  id: '/services/prefab',
  path: '/services/prefab',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEdiblePrintingRoute = ServicesEdiblePrintingRouteImport.update({
  id: '/services/edible-printing',
  path: '/services/edible-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdvertisingRoute = ServicesAdvertisingRouteImport.update({
  id: '/services/advertising',
  path: '/services/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const Services3dPrintingRoute = Services3dPrintingRouteImport.update({
  id: '/services/3d-printing',
  path: '/services/3d-printing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/3d-printing': typeof Services3dPrintingRoute
  '/services/advertising': typeof ServicesAdvertisingRoute
  '/services/edible-printing': typeof ServicesEdiblePrintingRoute
  '/services/prefab': typeof ServicesPrefabRoute
  '/services/solar': typeof ServicesSolarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/3d-printing': typeof Services3dPrintingRoute
  '/services/advertising': typeof ServicesAdvertisingRoute
  '/services/edible-printing': typeof ServicesEdiblePrintingRoute
  '/services/prefab': typeof ServicesPrefabRoute
  '/services/solar': typeof ServicesSolarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/3d-printing': typeof Services3dPrintingRoute
  '/services/advertising': typeof ServicesAdvertisingRoute
  '/services/edible-printing': typeof ServicesEdiblePrintingRoute
  '/services/prefab': typeof ServicesPrefabRoute
  '/services/solar': typeof ServicesSolarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/3d-printing'
    | '/services/advertising'
    | '/services/edible-printing'
    | '/services/prefab'
    | '/services/solar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/3d-printing'
    | '/services/advertising'
    | '/services/edible-printing'
    | '/services/prefab'
    | '/services/solar'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/3d-printing'
    | '/services/advertising'
    | '/services/edible-printing'
    | '/services/prefab'
    | '/services/solar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  Services3dPrintingRoute: typeof Services3dPrintingRoute
  ServicesAdvertisingRoute: typeof ServicesAdvertisingRoute
  ServicesEdiblePrintingRoute: typeof ServicesEdiblePrintingRoute
  ServicesPrefabRoute: typeof ServicesPrefabRoute
  ServicesSolarRoute: typeof ServicesSolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/solar': {
      id: '/services/solar'
      path: '/services/solar'
      fullPath: '/services/solar'
      preLoaderRoute: typeof ServicesSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/prefab': {
      id: '/services/prefab'
      path: '/services/prefab'
      fullPath: '/services/prefab'
      preLoaderRoute: typeof ServicesPrefabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/edible-printing': {
      id: '/services/edible-printing'
      path: '/services/edible-printing'
      fullPath: '/services/edible-printing'
      preLoaderRoute: typeof ServicesEdiblePrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/advertising': {
      id: '/services/advertising'
      path: '/services/advertising'
      fullPath: '/services/advertising'
      preLoaderRoute: typeof ServicesAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/3d-printing': {
      id: '/services/3d-printing'
      path: '/services/3d-printing'
      fullPath: '/services/3d-printing'
      preLoaderRoute: typeof Services3dPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  Services3dPrintingRoute: Services3dPrintingRoute,
  ServicesAdvertisingRoute: ServicesAdvertisingRoute,
  ServicesEdiblePrintingRoute: ServicesEdiblePrintingRoute,
  ServicesPrefabRoute: ServicesPrefabRoute,
  ServicesSolarRoute: ServicesSolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
